# Generated by Django 4.1.4 on 2022-12-24 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_from', models.CharField(max_length=100)),
                ('transport_to', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField()),
                ('asset_type', models.CharField(default='PACKAGE', max_length=15)),
                ('asset_senitivity', models.CharField(default='SENSITIVE', max_length=15)),
                ('asset_quantity', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=15)),
                ('deliver_to', models.CharField(default='Rabb', max_length=100)),
                ('faltu', models.CharField(max_length=50)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
