# Generated by Django 4.1.4 on 2022-12-24 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_asset_senitivity_assetrequest_asset_sensitivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_sensitivity',
            field=models.CharField(choices=[('highly_sensitive', 'HIGHLY SENSITIVE'), ('sensitive', 'SENSITIVE'), ('normal', 'NORMAL')], max_length=25),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'LAPTOP'), ('package', 'PACKAGE'), ('travel_bag', 'TRAVEL_BAG')], max_length=15),
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_from', models.CharField(max_length=100)),
                ('transport_to', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField()),
                ('travel_medium', models.CharField(choices=[('bus', 'BUS'), ('car', 'CAR'), ('train', 'TRAIN')], max_length=15)),
                ('asset_quantity', models.IntegerField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
