# Generated by Django 4.1.4 on 2022-12-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_assetrequest_asset_sensitivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelinfo',
            old_name='requester',
            new_name='rider',
        ),
    ]
