# Generated by Django 4.1.4 on 2022-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_requester_travelinfo_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='tatta',
            field=models.CharField(default='Haiga', max_length=15),
        ),
    ]
