# Generated by Django 4.1.4 on 2022-12-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_travelinfo_tatta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinfo',
            name='tatta',
        ),
    ]
