# Generated by Django 4.1.4 on 2022-12-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_travelinfo_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinfo',
            name='applicants',
            field=models.ManyToManyField(related_name='TravelInfo', to='users.assetrequest'),
        ),
    ]
